apiVersion: v1
kind: Pod
metadata:
  name: node-hello
spec:
  containers:
    - image: k8s-node-1/node-hello
      name: node-hello
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
